import type { OpenAPIObject } from 'openapi3-ts/oas31';
import crypto from 'node:crypto';

import type { RouteRecord } from '@motogram/shared';

function sha256(text: string): string {
  return crypto.createHash('sha256').update(text).digest('hex');
}

function groupNameFromPath(path: string): string {
  const clean = path.replace(/^\/v1\/?/, '/').replace(/^\/+/, '/');
  const seg = clean.split('/').filter(Boolean)[0] ?? 'root';
  if (seg === 'auth') return 'Auth';
  if (seg === 'users') return 'Users';
  if (seg === 'motorcycles') return 'Motorcycles';
  if (seg === 'posts') return 'Posts';
  if (seg === 'stories') return 'Stories';
  if (seg === 'comments') return 'Comments';
  if (seg === 'likes') return 'Likes';
  if (seg === 'follows') return 'Follows';
  if (seg === 'community' || seg === 'communities') return 'Community';
  if (seg === 'messaging') return 'Messaging';
  if (seg === 'party' || seg === 'parties') return 'Party';
  if (seg === 'emergency') return 'Emergency';
  if (seg === 'media') return 'Media';
  if (seg === 'map') return 'Map';
  if (seg === 'location') return 'Location';
  if (seg === 'notifications') return 'Notifications';
  if (seg === 'admin') return 'Admin';
  if (seg === 'feature-flags') return 'FeatureFlags';
  if (seg === 'ab-tests') return 'AbTests';
  if (seg === 'metrics') return 'Metrics';
  if (seg === 'healthz' || seg === 'livez' || seg === 'readyz') return 'Health';
  return seg[0] ? seg[0].toUpperCase() + seg.slice(1) : 'Other';
}

function anchorize(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

export function renderApiContractMd(doc: OpenAPIObject, routes: RouteRecord[], openapiJsonText: string): string {
  const byGroup = new Map<string, RouteRecord[]>();
  for (const r of routes) {
    const group = groupNameFromPath(r.path);
    const list = byGroup.get(group) ?? [];
    list.push(r);
    byGroup.set(group, list);
  }
  for (const [k, list] of byGroup.entries()) {
    list.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
    byGroup.set(k, list);
  }

  const groups = Array.from(byGroup.keys()).sort((a, b) => a.localeCompare(b));
  const endpointCount = routes.length;
  const hash = sha256(openapiJsonText);
  const ts = new Date().toISOString();

  const lines: string[] = [];
  lines.push('<!-- AUTO-GENERATED by apps/api/scripts/write-api-contract.ts. DO NOT EDIT. -->');
  lines.push('# Motogram API Contract');
  lines.push('');
  lines.push(`**Kaynak:** \`docs/openapi.json\` (sha256: \`${hash}\`)`);
  lines.push(`**Üretim tarihi:** \`${ts}\``);
  lines.push(`**OpenAPI:** \`${doc.openapi ?? '3.1.0'}\``);
  lines.push(`**API title:** \`${doc.info?.title ?? '@motogram/api'}\``);
  lines.push(`**API version:** \`${doc.info?.version ?? '0.0.0'}\``);
  lines.push(`**Endpoint sayısı:** \`${endpointCount}\``);
  lines.push('');
  lines.push('## İçindekiler');
  for (const g of groups) {
    lines.push(`- [${g}](#${anchorize(g)})`);
  }
  lines.push('');

  for (const g of groups) {
    lines.push(`## ${g}`);
    lines.push('');
    const list = byGroup.get(g) ?? [];
    for (const r of list) {
      const fullPath = `/v1${r.path.startsWith('/') ? r.path : `/${r.path}`}`.replace(/\/{2,}/g, '/');
      lines.push(`### ${r.method} ${fullPath}`);
      lines.push('');
      lines.push(`- **Auth**: ${r.auth ? 'Evet' : 'Hayır'}`);
      if (r.roles?.length) {
        lines.push(`- **Roles**: \`${r.roles.join(' | ')}\``);
      }
      if (r.requestBodySchema) {
        lines.push(`- **Request body schema**: \`${r.requestBodySchema}\``);
      } else {
        lines.push(`- **Request body schema**: _(yok)_`);
      }
      if (r.responseSchema) {
        lines.push(`- **Response**: \`${r.responseStatus ?? 200}\` → \`${r.responseSchema}\``);
      } else {
        lines.push(`- **Response**: \`${r.responseStatus ?? 200}\` → _(schema yok)_`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('## Notlar');
  lines.push('');
  lines.push('- Bu doküman **otomatik üretilir**. Değişiklik için `pnpm --filter @motogram/api openapi:generate` çalıştırıp commit’leyin.');
  lines.push('- WebSocket sözleşmesi bu dosyada yoktur. Bakınız: `docs/ws-contract.md`.');

  return lines.join('\n') + '\n';
}

